{% set version = "1.6.2" %}
{% set hash_type = "sha256" %}
{% set hash_value = "52d1e8db7521763135886ce1542bda4bfa6fb5bcfc591d59acd6811c218537ef" %}

package:
  name: 'npstreams'
  version: '{{ version }}'

source:
  fn: 'npstreams-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/n/npstreams/npstreams-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - pip
    - python>=3.6
  run:
    - python>=3.6
    - numpy>=1.12

test:
  requires:
    - scipy >=1.0.0
  imports:
    - npstreams
  commands:
    - python -m unittest discover -b

about:
  home: https://github.com/LaurentRDC/npstreams
  license: BSD-3-Clause
  license_family: BSD
  license_file: 'LICENSE.txt'
  summary: 'Streaming operations on NumPy arrays'
  description: |
    npstreams is an open-source Python package for streaming NumPy array operations.
    The goal is to provide tested routines that operate on streams (or generators) 
    of arrays instead of dense arrays. Streaming reduction operations (sums, averages, etc.) 
    can be implemented in constant memory, which in turns allows for easy parallelization.
  doc_url: 'https://npstreams.readthedocs.io'
  dev_url: 'https://github.com/LaurentRDC/npstreams'

extra:
  recipe-maintainers: 
    - LaurentRDC
